// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH1WnNdEc7TcwADWd-BcBSRH3ihyAC7Bo',
    appId: '1:444352676478:web:527ae5d7cb8da58ed90e2f',
    messagingSenderId: '444352676478',
    projectId: 'learnbot-ai-fce0d',
    authDomain: 'learnbot-ai-fce0d.firebaseapp.com',
    storageBucket: 'learnbot-ai-fce0d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA8ctgiwNJ93WVu8FuKBiK9yuJhWByIv0',
    appId: '1:444352676478:android:a5165d4d6e0945f2d90e2f',
    messagingSenderId: '444352676478',
    projectId: 'learnbot-ai-fce0d',
    storageBucket: 'learnbot-ai-fce0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKRc3RARYNR-vDbR1-pp3PO455NiJuO5s',
    appId: '1:444352676478:ios:86d0ba725446975fd90e2f',
    messagingSenderId: '444352676478',
    projectId: 'learnbot-ai-fce0d',
    storageBucket: 'learnbot-ai-fce0d.firebasestorage.app',
    iosBundleId: 'com.example.learnobot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKRc3RARYNR-vDbR1-pp3PO455NiJuO5s',
    appId: '1:444352676478:ios:86d0ba725446975fd90e2f',
    messagingSenderId: '444352676478',
    projectId: 'learnbot-ai-fce0d',
    storageBucket: 'learnbot-ai-fce0d.firebasestorage.app',
    iosBundleId: 'com.example.learnobot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH1WnNdEc7TcwADWd-BcBSRH3ihyAC7Bo',
    appId: '1:444352676478:web:325f2596f84e209cd90e2f',
    messagingSenderId: '444352676478',
    projectId: 'learnbot-ai-fce0d',
    authDomain: 'learnbot-ai-fce0d.firebaseapp.com',
    storageBucket: 'learnbot-ai-fce0d.firebasestorage.app',
  );
}
